"""Text for the invoice, ledger-statement and rate-card PDFs in the app's
languages (see utils/pdf_font.py for the fonts). Amounts use each language's own rupee word (Rs. where the script is Latin)."""
from datetime import datetime

EN = {
    "phone": "Phone: {v}", "strn": "STRN: {v}", "generated": "Generated on {v}",
    "thanks": "Thank you for your business!", "invoice_title": "TAX INVOICE",
    "invoice_no": "Invoice No: {v}", "date": "Date: {v}", "pay_status": "Payment Status: {v}",
    "pay_method": "Payment Method: {v}", "billed_to": "Billed To:", "address": "Address: {v}",
    "h_item": "Item", "h_qty": "Qty", "h_rate": "Rate", "h_taxable": "Taxable", "h_taxpct": "Tax%",
    "h_tax": "Tax", "h_hsn": "HSN", "h_desc": "Description", "h_total": "Total",
    "inc_note": "* Prices include Sales Tax; tax shown separately for reference.",
    "t_taxable": "Total Taxable Value", "t_addtax": "Add: Sales Tax", "t_discount": "Less: Discount",
    "t_roundoff": "Round Off", "t_grand": "GRAND TOTAL", "words": "Amount in words: {v}",
    "hsn_summary": "HSN Summary:", "amount_paid": "Amount Paid: Rs. {v}", "outstanding": "Outstanding: Rs. {v}",
    "items_lbl": "Items:", "no_items": "No items", "total_rs": "Total: Rs. {v}",
    "pay_jazz": "Pay via JazzCash: {v}", "for_shop": "For {v}", "signatory": "Authorised Signatory",
    "computer_invoice": "This is a computer-generated invoice.",
    "st_paid": "Paid", "st_unpaid": "Unpaid", "st_partial": "Partial",
    "m_cash": "Cash", "m_bank_transfer": "Bank Transfer", "m_cheque": "Cheque",
    "l_customer_title": "CUSTOMER LEDGER STATEMENT", "l_supplier_title": "SUPPLIER LEDGER STATEMENT",
    "customer": "Customer: {v}", "supplier": "Supplier: {v}", "credit_limit": "Credit Limit: Rs. {v}",
    "no_bills": "No bills found for this customer.", "no_purchases": "No purchases recorded from this supplier.",
    "h_date": "Date", "h_bill": "Bill #", "h_receipt": "Recpt #", "h_amount": "Amount", "h_paid": "Paid",
    "h_balance": "Balance", "total_billed": "Total Billed: Rs. {v}", "total_paid": "Total Paid: Rs. {v}",
    "outstanding_balance": "Outstanding Balance: Rs. {v}", "total_purchased": "Total Purchased: Rs. {v}",
    "outstanding_payable": "Outstanding Payable: Rs. {v}",
    "computer_statement": "This is a computer-generated statement.", "more": "+{v} more",
    "rate_title": "RATE CARD", "no_items_found": "No items found.", "uncategorized": "Uncategorized",
    "h_unit": "Unit", "h_price": "Price (Rs.)", "disclaimer": "Prices subject to change without notice.",
    "ph_title": "PRICE HISTORY", "sh_title": "STOCK ADJUSTMENT HISTORY", "h_cost": "Cost price",
    "h_change": "Change", "h_by": "By", "h_prev": "Previous", "h_new": "New", "h_note": "Note",
    "no_history": "No entries recorded.",
}

_T = {
    "ar": {
        "phone": "الهاتف: {v}", "strn": "الرقم الضريبي: {v}", "generated": "تاريخ الإنشاء: {v}",
        "thanks": "شكراً لتعاملكم معنا!", "invoice_title": "فاتورة ضريبية", "invoice_no": "رقم الفاتورة: {v}",
        "date": "التاريخ: {v}", "pay_status": "حالة الدفع: {v}", "pay_method": "طريقة الدفع: {v}",
        "billed_to": "الفاتورة إلى:", "address": "العنوان: {v}", "h_item": "الصنف", "h_qty": "الكمية",
        "h_rate": "السعر", "h_taxable": "الخاضع", "h_taxpct": "الضريبة%", "h_tax": "الضريبة", "h_hsn": "HSN",
        "h_desc": "الوصف", "h_total": "الإجمالي",
        "inc_note": "* الأسعار شاملة ضريبة المبيعات؛ الضريبة موضّحة بشكل منفصل للمرجع.",
        "t_taxable": "إجمالي القيمة الخاضعة للضريبة", "t_addtax": "يضاف: ضريبة المبيعات", "t_discount": "ناقص: الخصم",
        "t_roundoff": "التقريب", "t_grand": "الإجمالي النهائي", "hsn_summary": "ملخص HSN:",
        "amount_paid": "المبلغ المدفوع: {v} روبية", "outstanding": "المتبقي: {v} روبية", "items_lbl": "الأصناف:",
        "no_items": "لا توجد أصناف", "total_rs": "الإجمالي: {v} روبية", "pay_jazz": "ادفع عبر جاز كاش: {v}",
        "for_shop": "لصالح {v}", "signatory": "المفوّض بالتوقيع", "computer_invoice": "هذه فاتورة صادرة من الحاسوب.",
        "st_paid": "مدفوعة", "st_unpaid": "غير مدفوعة", "st_partial": "مدفوعة جزئياً", "m_cash": "نقداً",
        "m_bank_transfer": "تحويل بنكي", "m_cheque": "شيك", "l_customer_title": "كشف حساب العميل",
        "l_supplier_title": "كشف حساب المورّد", "customer": "العميل: {v}", "supplier": "المورّد: {v}",
        "credit_limit": "حد الائتمان: {v} روبية", "no_bills": "لا توجد فواتير لهذا العميل.",
        "no_purchases": "لا توجد مشتريات مسجلة من هذا المورّد.", "h_date": "التاريخ", "h_bill": "رقم الفاتورة",
        "h_receipt": "رقم الإيصال", "h_amount": "المبلغ", "h_paid": "المدفوع", "h_balance": "الرصيد",
        "total_billed": "إجمالي الفواتير: {v} روبية", "total_paid": "إجمالي المدفوع: {v} روبية",
        "outstanding_balance": "الرصيد المستحق: {v} روبية", "total_purchased": "إجمالي المشتريات: {v} روبية",
        "outstanding_payable": "المستحق للدفع: {v} روبية", "computer_statement": "هذا كشف حساب صادر من الحاسوب.",
        "more": "+{v} أخرى", "rate_title": "قائمة الأسعار", "no_items_found": "لا توجد أصناف.",
        "uncategorized": "غير مصنّف", "h_unit": "الوحدة", "h_price": "السعر (روبية)",
        "disclaimer": "الأسعار قابلة للتغيير دون إشعار مسبق.",
    },
    "bn": {
        "phone": "ফোন: {v}", "strn": "STRN: {v}", "generated": "তৈরির তারিখ: {v}",
        "thanks": "আপনার ব্যবসার জন্য ধন্যবাদ!", "invoice_title": "কর চালান", "invoice_no": "চালান নং: {v}",
        "date": "তারিখ: {v}", "pay_status": "পেমেন্টের অবস্থা: {v}", "pay_method": "পেমেন্ট পদ্ধতি: {v}",
        "billed_to": "বিল প্রাপক:", "address": "ঠিকানা: {v}", "h_item": "পণ্য", "h_qty": "পরিমাণ",
        "h_rate": "দর", "h_taxable": "করযোগ্য", "h_taxpct": "কর%", "h_tax": "কর", "h_hsn": "HSN",
        "h_desc": "বিবরণ", "h_total": "মোট",
        "inc_note": "* দামে বিক্রয় কর অন্তর্ভুক্ত; রেফারেন্সের জন্য কর আলাদা দেখানো হয়েছে।",
        "t_taxable": "মোট করযোগ্য মূল্য", "t_addtax": "যোগ: বিক্রয় কর", "t_discount": "বাদ: ছাড়",
        "t_roundoff": "পূর্ণসংখ্যায় সমন্বয়", "t_grand": "সর্বমোট", "hsn_summary": "HSN সারাংশ:",
        "amount_paid": "পরিশোধিত: {v} রুপি", "outstanding": "বকেয়া: {v} রুপি", "items_lbl": "পণ্য:",
        "no_items": "কোনো পণ্য নেই", "total_rs": "মোট: {v} রুপি", "pay_jazz": "JazzCash-এ পরিশোধ করুন: {v}",
        "for_shop": "{v}-এর পক্ষে", "signatory": "অনুমোদিত স্বাক্ষরকারী",
        "computer_invoice": "এটি কম্পিউটার-নির্মিত চালান।", "st_paid": "পরিশোধিত", "st_unpaid": "অপরিশোধিত",
        "st_partial": "আংশিক", "m_cash": "নগদ", "m_bank_transfer": "ব্যাংক ট্রান্সফার", "m_cheque": "চেক",
        "l_customer_title": "গ্রাহকের লেজার বিবরণী", "l_supplier_title": "সরবরাহকারীর লেজার বিবরণী",
        "customer": "গ্রাহক: {v}", "supplier": "সরবরাহকারী: {v}", "credit_limit": "ক্রেডিট সীমা: {v} রুপি",
        "no_bills": "এই গ্রাহকের কোনো বিল পাওয়া যায়নি।", "no_purchases": "এই সরবরাহকারীর কাছ থেকে কোনো ক্রয় নথিভুক্ত নেই।",
        "h_date": "তারিখ", "h_bill": "বিল নং", "h_receipt": "রসিদ নং", "h_amount": "পরিমাণ", "h_paid": "পরিশোধিত",
        "h_balance": "ব্যালেন্স", "total_billed": "মোট বিল: {v} রুপি", "total_paid": "মোট পরিশোধিত: {v} রুপি",
        "outstanding_balance": "বকেয়া ব্যালেন্স: {v} রুপি", "total_purchased": "মোট ক্রয়: {v} রুপি",
        "outstanding_payable": "পরিশোধযোগ্য বকেয়া: {v} রুপি", "computer_statement": "এটি কম্পিউটার-নির্মিত বিবরণী।",
        "more": "আরও +{v}", "rate_title": "দরপত্র", "no_items_found": "কোনো পণ্য পাওয়া যায়নি।",
        "uncategorized": "বিভাগহীন", "h_unit": "একক", "h_price": "দাম (রুপি)",
        "disclaimer": "পূর্ব নোটিশ ছাড়াই দাম পরিবর্তন হতে পারে।",
    },
    "de": {
        "phone": "Telefon: {v}", "strn": "STRN: {v}", "generated": "Erstellt am {v}",
        "thanks": "Vielen Dank für Ihren Einkauf!", "invoice_title": "STEUERRECHNUNG", "invoice_no": "Rechnungsnr.: {v}",
        "date": "Datum: {v}", "pay_status": "Zahlungsstatus: {v}", "pay_method": "Zahlungsart: {v}",
        "billed_to": "Rechnung an:", "address": "Adresse: {v}", "h_item": "Artikel", "h_qty": "Menge",
        "h_rate": "Preis", "h_taxable": "Steuerpfl.", "h_taxpct": "Steuer%", "h_tax": "Steuer", "h_hsn": "HSN",
        "h_desc": "Beschreibung", "h_total": "Gesamt",
        "inc_note": "* Preise enthalten Umsatzsteuer; die Steuer ist zur Information gesondert ausgewiesen.",
        "t_taxable": "Steuerpflichtiger Gesamtwert", "t_addtax": "Zzgl.: Umsatzsteuer", "t_discount": "Abzgl.: Rabatt",
        "t_roundoff": "Rundung", "t_grand": "GESAMTSUMME", "hsn_summary": "HSN-Zusammenfassung:",
        "amount_paid": "Bezahlt: Rs. {v}", "outstanding": "Offen: Rs. {v}", "items_lbl": "Artikel:",
        "no_items": "Keine Artikel", "total_rs": "Gesamt: Rs. {v}", "pay_jazz": "Zahlen mit JazzCash: {v}",
        "for_shop": "Für {v}", "signatory": "Zeichnungsberechtigter",
        "computer_invoice": "Dies ist eine computergenerierte Rechnung.", "st_paid": "Bezahlt", "st_unpaid": "Unbezahlt",
        "st_partial": "Teilweise", "m_cash": "Bar", "m_bank_transfer": "Überweisung", "m_cheque": "Scheck",
        "l_customer_title": "KUNDENKONTOAUSZUG", "l_supplier_title": "LIEFERANTENKONTOAUSZUG",
        "customer": "Kunde: {v}", "supplier": "Lieferant: {v}", "credit_limit": "Kreditlimit: Rs. {v}",
        "no_bills": "Keine Rechnungen für diesen Kunden gefunden.", "no_purchases": "Keine Einkäufe bei diesem Lieferanten erfasst.",
        "h_date": "Datum", "h_bill": "Rechn.-Nr.", "h_receipt": "Beleg-Nr.", "h_amount": "Betrag", "h_paid": "Bezahlt",
        "h_balance": "Saldo", "total_billed": "Gesamt berechnet: Rs. {v}", "total_paid": "Gesamt bezahlt: Rs. {v}",
        "outstanding_balance": "Offener Saldo: Rs. {v}", "total_purchased": "Gesamt eingekauft: Rs. {v}",
        "outstanding_payable": "Offene Verbindlichkeit: Rs. {v}", "computer_statement": "Dies ist ein computergenerierter Auszug.",
        "more": "+{v} weitere", "rate_title": "PREISLISTE", "no_items_found": "Keine Artikel gefunden.",
        "uncategorized": "Ohne Kategorie", "h_unit": "Einheit", "h_price": "Preis (Rs.)",
        "disclaimer": "Preisänderungen ohne Vorankündigung vorbehalten.",
    },
    "es": {
        "phone": "Teléfono: {v}", "strn": "STRN: {v}", "generated": "Generado el {v}",
        "thanks": "¡Gracias por su compra!", "invoice_title": "FACTURA FISCAL", "invoice_no": "N.º de factura: {v}",
        "date": "Fecha: {v}", "pay_status": "Estado del pago: {v}", "pay_method": "Forma de pago: {v}",
        "billed_to": "Facturado a:", "address": "Dirección: {v}", "h_item": "Artículo", "h_qty": "Cant.",
        "h_rate": "Precio", "h_taxable": "Base", "h_taxpct": "Imp.%", "h_tax": "Impuesto", "h_hsn": "HSN",
        "h_desc": "Descripción", "h_total": "Total",
        "inc_note": "* Los precios incluyen el impuesto sobre las ventas; el impuesto se muestra aparte como referencia.",
        "t_taxable": "Total base imponible", "t_addtax": "Más: impuesto sobre las ventas", "t_discount": "Menos: descuento",
        "t_roundoff": "Redondeo", "t_grand": "TOTAL GENERAL", "hsn_summary": "Resumen HSN:",
        "amount_paid": "Importe pagado: Rs. {v}", "outstanding": "Pendiente: Rs. {v}", "items_lbl": "Artículos:",
        "no_items": "Sin artículos", "total_rs": "Total: Rs. {v}", "pay_jazz": "Pague con JazzCash: {v}",
        "for_shop": "Por {v}", "signatory": "Firmante autorizado",
        "computer_invoice": "Esta es una factura generada por computadora.", "st_paid": "Pagada", "st_unpaid": "Sin pagar",
        "st_partial": "Parcial", "m_cash": "Efectivo", "m_bank_transfer": "Transferencia bancaria", "m_cheque": "Cheque",
        "l_customer_title": "ESTADO DE CUENTA DEL CLIENTE", "l_supplier_title": "ESTADO DE CUENTA DEL PROVEEDOR",
        "customer": "Cliente: {v}", "supplier": "Proveedor: {v}", "credit_limit": "Límite de crédito: Rs. {v}",
        "no_bills": "No se encontraron facturas para este cliente.", "no_purchases": "No hay compras registradas a este proveedor.",
        "h_date": "Fecha", "h_bill": "N.º fact.", "h_receipt": "N.º recibo", "h_amount": "Importe", "h_paid": "Pagado",
        "h_balance": "Saldo", "total_billed": "Total facturado: Rs. {v}", "total_paid": "Total pagado: Rs. {v}",
        "outstanding_balance": "Saldo pendiente: Rs. {v}", "total_purchased": "Total comprado: Rs. {v}",
        "outstanding_payable": "Pendiente por pagar: Rs. {v}", "computer_statement": "Este es un estado de cuenta generado por computadora.",
        "more": "+{v} más", "rate_title": "LISTA DE PRECIOS", "no_items_found": "No se encontraron artículos.",
        "uncategorized": "Sin categoría", "h_unit": "Unidad", "h_price": "Precio (Rs.)",
        "disclaimer": "Precios sujetos a cambio sin previo aviso.",
    },
    "fa": {
        "phone": "تلفن: {v}", "strn": "STRN: {v}", "generated": "تاریخ تولید: {v}",
        "thanks": "از خرید شما سپاسگزاریم!", "invoice_title": "فاکتور مالیاتی", "invoice_no": "شماره فاکتور: {v}",
        "date": "تاریخ: {v}", "pay_status": "وضعیت پرداخت: {v}", "pay_method": "روش پرداخت: {v}",
        "billed_to": "صورتحساب برای:", "address": "نشانی: {v}", "h_item": "کالا", "h_qty": "تعداد",
        "h_rate": "نرخ", "h_taxable": "مشمول", "h_taxpct": "مالیات%", "h_tax": "مالیات", "h_hsn": "HSN",
        "h_desc": "شرح", "h_total": "جمع",
        "inc_note": "* قیمت‌ها شامل مالیات فروش است؛ مالیات برای اطلاع جداگانه نشان داده شده است.",
        "t_taxable": "جمع ارزش مشمول مالیات", "t_addtax": "افزوده: مالیات فروش", "t_discount": "کسر: تخفیف",
        "t_roundoff": "گرد کردن", "t_grand": "جمع کل", "hsn_summary": "خلاصه HSN:",
        "amount_paid": "مبلغ پرداخت‌شده: {v} روپیه", "outstanding": "مانده: {v} روپیه", "items_lbl": "اقلام:",
        "no_items": "بدون قلم", "total_rs": "جمع: {v} روپیه", "pay_jazz": "پرداخت از طریق JazzCash: {v}",
        "for_shop": "از طرف {v}", "signatory": "امضاکننده مجاز", "computer_invoice": "این فاکتور به‌صورت رایانه‌ای صادر شده است.",
        "st_paid": "پرداخت‌شده", "st_unpaid": "پرداخت‌نشده", "st_partial": "جزئی", "m_cash": "نقد",
        "m_bank_transfer": "انتقال بانکی", "m_cheque": "چک", "l_customer_title": "صورت‌حساب مشتری",
        "l_supplier_title": "صورت‌حساب تأمین‌کننده", "customer": "مشتری: {v}", "supplier": "تأمین‌کننده: {v}",
        "credit_limit": "سقف اعتبار: {v} روپیه", "no_bills": "فاکتوری برای این مشتری یافت نشد.",
        "no_purchases": "خریدی از این تأمین‌کننده ثبت نشده است.", "h_date": "تاریخ", "h_bill": "شماره فاکتور",
        "h_receipt": "شماره رسید", "h_amount": "مبلغ", "h_paid": "پرداخت‌شده", "h_balance": "مانده",
        "total_billed": "جمع صورتحساب‌ها: {v} روپیه", "total_paid": "جمع پرداختی: {v} روپیه",
        "outstanding_balance": "مانده معوق: {v} روپیه", "total_purchased": "جمع خرید: {v} روپیه",
        "outstanding_payable": "مانده قابل پرداخت: {v} روپیه", "computer_statement": "این صورت‌حساب به‌صورت رایانه‌ای صادر شده است.",
        "more": "+{v} مورد دیگر", "rate_title": "لیست قیمت", "no_items_found": "کالایی یافت نشد.",
        "uncategorized": "بدون دسته", "h_unit": "واحد", "h_price": "قیمت (روپیه)",
        "disclaimer": "قیمت‌ها ممکن است بدون اطلاع قبلی تغییر کنند.",
    },
    "fr": {
        "phone": "Téléphone : {v}", "strn": "STRN : {v}", "generated": "Généré le {v}",
        "thanks": "Merci pour votre confiance !", "invoice_title": "FACTURE FISCALE", "invoice_no": "N° de facture : {v}",
        "date": "Date : {v}", "pay_status": "Statut du paiement : {v}", "pay_method": "Mode de paiement : {v}",
        "billed_to": "Facturé à :", "address": "Adresse : {v}", "h_item": "Article", "h_qty": "Qté",
        "h_rate": "Prix", "h_taxable": "Base", "h_taxpct": "Taxe%", "h_tax": "Taxe", "h_hsn": "HSN",
        "h_desc": "Description", "h_total": "Total",
        "inc_note": "* Les prix incluent la taxe de vente ; la taxe est indiquée séparément à titre de référence.",
        "t_taxable": "Total base imposable", "t_addtax": "Plus : taxe de vente", "t_discount": "Moins : remise",
        "t_roundoff": "Arrondi", "t_grand": "TOTAL GÉNÉRAL", "hsn_summary": "Récapitulatif HSN :",
        "amount_paid": "Montant payé : Rs. {v}", "outstanding": "Reste dû : Rs. {v}", "items_lbl": "Articles :",
        "no_items": "Aucun article", "total_rs": "Total : Rs. {v}", "pay_jazz": "Payer via JazzCash : {v}",
        "for_shop": "Pour {v}", "signatory": "Signataire autorisé",
        "computer_invoice": "Ceci est une facture générée par ordinateur.", "st_paid": "Payée", "st_unpaid": "Impayée",
        "st_partial": "Partielle", "m_cash": "Espèces", "m_bank_transfer": "Virement bancaire", "m_cheque": "Chèque",
        "l_customer_title": "RELEVÉ DE COMPTE CLIENT", "l_supplier_title": "RELEVÉ DE COMPTE FOURNISSEUR",
        "customer": "Client : {v}", "supplier": "Fournisseur : {v}", "credit_limit": "Limite de crédit : Rs. {v}",
        "no_bills": "Aucune facture trouvée pour ce client.", "no_purchases": "Aucun achat enregistré auprès de ce fournisseur.",
        "h_date": "Date", "h_bill": "N° fact.", "h_receipt": "N° reçu", "h_amount": "Montant", "h_paid": "Payé",
        "h_balance": "Solde", "total_billed": "Total facturé : Rs. {v}", "total_paid": "Total payé : Rs. {v}",
        "outstanding_balance": "Solde dû : Rs. {v}", "total_purchased": "Total acheté : Rs. {v}",
        "outstanding_payable": "Reste à payer : Rs. {v}", "computer_statement": "Ceci est un relevé généré par ordinateur.",
        "more": "+{v} de plus", "rate_title": "GRILLE TARIFAIRE", "no_items_found": "Aucun article trouvé.",
        "uncategorized": "Sans catégorie", "h_unit": "Unité", "h_price": "Prix (Rs.)",
        "disclaimer": "Prix susceptibles de changer sans préavis.",
    },
    "hi": {
        "phone": "फ़ोन: {v}", "strn": "STRN: {v}", "generated": "बनाने की तिथि: {v}",
        "thanks": "आपके व्यापार के लिए धन्यवाद!", "invoice_title": "कर चालान", "invoice_no": "चालान संख्या: {v}",
        "date": "तिथि: {v}", "pay_status": "भुगतान की स्थिति: {v}", "pay_method": "भुगतान का तरीका: {v}",
        "billed_to": "बिल प्राप्तकर्ता:", "address": "पता: {v}", "h_item": "वस्तु", "h_qty": "मात्रा",
        "h_rate": "दर", "h_taxable": "कर योग्य", "h_taxpct": "कर%", "h_tax": "कर", "h_hsn": "HSN",
        "h_desc": "विवरण", "h_total": "कुल",
        "inc_note": "* कीमतों में बिक्री कर शामिल है; संदर्भ के लिए कर अलग से दिखाया गया है।",
        "t_taxable": "कुल कर योग्य मूल्य", "t_addtax": "जोड़ें: बिक्री कर", "t_discount": "घटाएँ: छूट",
        "t_roundoff": "पूर्णांक समायोजन", "t_grand": "कुल योग", "hsn_summary": "HSN सारांश:",
        "amount_paid": "भुगतान की गई राशि: रु {v}", "outstanding": "बकाया: रु {v}", "items_lbl": "वस्तुएँ:",
        "no_items": "कोई वस्तु नहीं", "total_rs": "कुल: रु {v}", "pay_jazz": "JazzCash से भुगतान करें: {v}",
        "for_shop": "{v} के लिए", "signatory": "अधिकृत हस्ताक्षरकर्ता",
        "computer_invoice": "यह कंप्यूटर द्वारा बनाया गया चालान है।", "st_paid": "भुगतान किया", "st_unpaid": "बकाया",
        "st_partial": "आंशिक", "m_cash": "नकद", "m_bank_transfer": "बैंक ट्रांसफ़र", "m_cheque": "चेक",
        "l_customer_title": "ग्राहक खाता विवरण", "l_supplier_title": "आपूर्तिकर्ता खाता विवरण",
        "customer": "ग्राहक: {v}", "supplier": "आपूर्तिकर्ता: {v}", "credit_limit": "क्रेडिट सीमा: रु {v}",
        "no_bills": "इस ग्राहक के कोई बिल नहीं मिले।", "no_purchases": "इस आपूर्तिकर्ता से कोई खरीद दर्ज नहीं है।",
        "h_date": "तिथि", "h_bill": "बिल सं.", "h_receipt": "रसीद सं.", "h_amount": "राशि", "h_paid": "चुकाया",
        "h_balance": "शेष", "total_billed": "कुल बिल: रु {v}", "total_paid": "कुल भुगतान: रु {v}",
        "outstanding_balance": "बकाया शेष: रु {v}", "total_purchased": "कुल खरीद: रु {v}",
        "outstanding_payable": "देय बकाया: रु {v}", "computer_statement": "यह कंप्यूटर द्वारा बनाया गया विवरण है।",
        "more": "+{v} और", "rate_title": "दर सूची", "no_items_found": "कोई वस्तु नहीं मिली।",
        "uncategorized": "अवर्गीकृत", "h_unit": "इकाई", "h_price": "कीमत (रु)",
        "disclaimer": "कीमतें बिना सूचना के बदल सकती हैं।",
    },
    "id": {
        "phone": "Telepon: {v}", "strn": "STRN: {v}", "generated": "Dibuat pada {v}",
        "thanks": "Terima kasih atas kepercayaan Anda!", "invoice_title": "FAKTUR PAJAK", "invoice_no": "No. Faktur: {v}",
        "date": "Tanggal: {v}", "pay_status": "Status Pembayaran: {v}", "pay_method": "Metode Pembayaran: {v}",
        "billed_to": "Ditagihkan kepada:", "address": "Alamat: {v}", "h_item": "Barang", "h_qty": "Jml",
        "h_rate": "Harga", "h_taxable": "DPP", "h_taxpct": "Pajak%", "h_tax": "Pajak", "h_hsn": "HSN",
        "h_desc": "Deskripsi", "h_total": "Total",
        "inc_note": "* Harga sudah termasuk pajak penjualan; pajak ditampilkan terpisah sebagai referensi.",
        "t_taxable": "Total Nilai Kena Pajak", "t_addtax": "Tambah: Pajak Penjualan", "t_discount": "Kurang: Diskon",
        "t_roundoff": "Pembulatan", "t_grand": "TOTAL AKHIR", "hsn_summary": "Ringkasan HSN:",
        "amount_paid": "Dibayar: Rs. {v}", "outstanding": "Sisa: Rs. {v}", "items_lbl": "Barang:",
        "no_items": "Tidak ada barang", "total_rs": "Total: Rs. {v}", "pay_jazz": "Bayar lewat JazzCash: {v}",
        "for_shop": "Untuk {v}", "signatory": "Penandatangan Resmi",
        "computer_invoice": "Ini adalah faktur yang dibuat komputer.", "st_paid": "Lunas", "st_unpaid": "Belum dibayar",
        "st_partial": "Sebagian", "m_cash": "Tunai", "m_bank_transfer": "Transfer Bank", "m_cheque": "Cek",
        "l_customer_title": "LAPORAN BUKU BESAR PELANGGAN", "l_supplier_title": "LAPORAN BUKU BESAR PEMASOK",
        "customer": "Pelanggan: {v}", "supplier": "Pemasok: {v}", "credit_limit": "Batas Kredit: Rs. {v}",
        "no_bills": "Tidak ada tagihan untuk pelanggan ini.", "no_purchases": "Tidak ada pembelian tercatat dari pemasok ini.",
        "h_date": "Tanggal", "h_bill": "No. Tagihan", "h_receipt": "No. Terima", "h_amount": "Jumlah", "h_paid": "Dibayar",
        "h_balance": "Saldo", "total_billed": "Total Ditagih: Rs. {v}", "total_paid": "Total Dibayar: Rs. {v}",
        "outstanding_balance": "Saldo Belum Dibayar: Rs. {v}", "total_purchased": "Total Pembelian: Rs. {v}",
        "outstanding_payable": "Utang Belum Dibayar: Rs. {v}", "computer_statement": "Ini adalah laporan yang dibuat komputer.",
        "more": "+{v} lagi", "rate_title": "DAFTAR HARGA", "no_items_found": "Tidak ada barang ditemukan.",
        "uncategorized": "Tanpa Kategori", "h_unit": "Satuan", "h_price": "Harga (Rs.)",
        "disclaimer": "Harga dapat berubah tanpa pemberitahuan.",
    },
    "pa": {
        "phone": "ਫ਼ੋਨ: {v}", "strn": "STRN: {v}", "generated": "ਬਣਾਉਣ ਦੀ ਤਾਰੀਖ਼: {v}",
        "thanks": "ਤੁਹਾਡੇ ਕਾਰੋਬਾਰ ਲਈ ਧੰਨਵਾਦ!", "invoice_title": "ਟੈਕਸ ਇਨਵੌਇਸ", "invoice_no": "ਇਨਵੌਇਸ ਨੰ: {v}",
        "date": "ਤਾਰੀਖ਼: {v}", "pay_status": "ਭੁਗਤਾਨ ਦੀ ਸਥਿਤੀ: {v}", "pay_method": "ਭੁਗਤਾਨ ਦਾ ਤਰੀਕਾ: {v}",
        "billed_to": "ਬਿੱਲ ਪ੍ਰਾਪਤਕਰਤਾ:", "address": "ਪਤਾ: {v}", "h_item": "ਸਮਾਨ", "h_qty": "ਮਾਤਰਾ",
        "h_rate": "ਦਰ", "h_taxable": "ਟੈਕਸਯੋਗ", "h_taxpct": "ਟੈਕਸ%", "h_tax": "ਟੈਕਸ", "h_hsn": "HSN",
        "h_desc": "ਵੇਰਵਾ", "h_total": "ਕੁੱਲ",
        "inc_note": "* ਕੀਮਤਾਂ ਵਿੱਚ ਸੇਲਜ਼ ਟੈਕਸ ਸ਼ਾਮਲ ਹੈ; ਹਵਾਲੇ ਲਈ ਟੈਕਸ ਵੱਖਰਾ ਦਿਖਾਇਆ ਗਿਆ ਹੈ।",
        "t_taxable": "ਕੁੱਲ ਟੈਕਸਯੋਗ ਮੁੱਲ", "t_addtax": "ਜੋੜੋ: ਸੇਲਜ਼ ਟੈਕਸ", "t_discount": "ਘਟਾਓ: ਛੋਟ",
        "t_roundoff": "ਗੋਲ ਅੰਕ", "t_grand": "ਕੁੱਲ ਜੋੜ", "hsn_summary": "HSN ਸਾਰ:",
        "amount_paid": "ਭੁਗਤਾਨ ਕੀਤੀ ਰਕਮ: ਰੁ {v}", "outstanding": "ਬਕਾਇਆ: ਰੁ {v}", "items_lbl": "ਸਮਾਨ:",
        "no_items": "ਕੋਈ ਸਮਾਨ ਨਹੀਂ", "total_rs": "ਕੁੱਲ: ਰੁ {v}", "pay_jazz": "JazzCash ਰਾਹੀਂ ਭੁਗਤਾਨ ਕਰੋ: {v}",
        "for_shop": "{v} ਲਈ", "signatory": "ਅਧਿਕਾਰਤ ਦਸਤਖ਼ਤਕਰਤਾ",
        "computer_invoice": "ਇਹ ਕੰਪਿਊਟਰ ਵੱਲੋਂ ਬਣਾਇਆ ਇਨਵੌਇਸ ਹੈ।", "st_paid": "ਭੁਗਤਾਨ ਹੋਇਆ", "st_unpaid": "ਬਕਾਇਆ",
        "st_partial": "ਅੰਸ਼ਕ", "m_cash": "ਨਕਦ", "m_bank_transfer": "ਬੈਂਕ ਟ੍ਰਾਂਸਫ਼ਰ", "m_cheque": "ਚੈੱਕ",
        "l_customer_title": "ਗਾਹਕ ਖਾਤਾ ਵੇਰਵਾ", "l_supplier_title": "ਸਪਲਾਇਰ ਖਾਤਾ ਵੇਰਵਾ",
        "customer": "ਗਾਹਕ: {v}", "supplier": "ਸਪਲਾਇਰ: {v}", "credit_limit": "ਕ੍ਰੈਡਿਟ ਸੀਮਾ: ਰੁ {v}",
        "no_bills": "ਇਸ ਗਾਹਕ ਦਾ ਕੋਈ ਬਿੱਲ ਨਹੀਂ ਮਿਲਿਆ।", "no_purchases": "ਇਸ ਸਪਲਾਇਰ ਤੋਂ ਕੋਈ ਖਰੀਦ ਦਰਜ ਨਹੀਂ ਹੈ।",
        "h_date": "ਤਾਰੀਖ਼", "h_bill": "ਬਿੱਲ ਨੰ.", "h_receipt": "ਰਸੀਦ ਨੰ.", "h_amount": "ਰਕਮ", "h_paid": "ਅਦਾ ਕੀਤਾ",
        "h_balance": "ਬਕਾਇਆ", "total_billed": "ਕੁੱਲ ਬਿੱਲ: ਰੁ {v}", "total_paid": "ਕੁੱਲ ਭੁਗਤਾਨ: ਰੁ {v}",
        "outstanding_balance": "ਬਕਾਇਆ ਰਕਮ: ਰੁ {v}", "total_purchased": "ਕੁੱਲ ਖਰੀਦ: ਰੁ {v}",
        "outstanding_payable": "ਦੇਣਯੋਗ ਬਕਾਇਆ: ਰੁ {v}", "computer_statement": "ਇਹ ਕੰਪਿਊਟਰ ਵੱਲੋਂ ਬਣਾਇਆ ਵੇਰਵਾ ਹੈ।",
        "more": "+{v} ਹੋਰ", "rate_title": "ਰੇਟ ਸੂਚੀ", "no_items_found": "ਕੋਈ ਸਮਾਨ ਨਹੀਂ ਮਿਲਿਆ।",
        "uncategorized": "ਬਿਨਾਂ ਸ਼੍ਰੇਣੀ", "h_unit": "ਇਕਾਈ", "h_price": "ਕੀਮਤ (ਰੁ)",
        "disclaimer": "ਕੀਮਤਾਂ ਬਿਨਾਂ ਸੂਚਨਾ ਦੇ ਬਦਲ ਸਕਦੀਆਂ ਹਨ।",
    },
    "ps": {
        "phone": "تلیفون: {v}", "strn": "STRN: {v}", "generated": "د جوړېدو نېټه: {v}",
        "thanks": "ستاسو د سوداګرۍ مننه!", "invoice_title": "مالیاتي بل", "invoice_no": "د بل شمېره: {v}",
        "date": "نېټه: {v}", "pay_status": "د ورکړې حالت: {v}", "pay_method": "د ورکړې طریقه: {v}",
        "billed_to": "بل ته:", "address": "پته: {v}", "h_item": "توکی", "h_qty": "شمېر",
        "h_rate": "نرخ", "h_taxable": "مالیې وړ", "h_taxpct": "مالیه%", "h_tax": "مالیه", "h_hsn": "HSN",
        "h_desc": "تفصیل", "h_total": "ټول",
        "inc_note": "* بیې د پلور مالیه لري؛ مالیه د معلوماتو لپاره جلا ښودل شوې.",
        "t_taxable": "د مالیې وړ ټوله ارزښت", "t_addtax": "ورزیات: د پلور مالیه", "t_discount": "کم: تخفیف",
        "t_roundoff": "ګرد کول", "t_grand": "مجموعي ټول", "hsn_summary": "د HSN لنډیز:",
        "amount_paid": "ورکړل شوې پیسې: {v} روپۍ", "outstanding": "پاتې: {v} روپۍ", "items_lbl": "توکي:",
        "no_items": "هیڅ توکی نشته", "total_rs": "ټول: {v} روپۍ", "pay_jazz": "د JazzCash له لارې ورکړه: {v}",
        "for_shop": "د {v} لپاره", "signatory": "واک لرونکی لاسلیک کوونکی",
        "computer_invoice": "دا د کمپیوټر له خوا جوړ شوی بل دی.", "st_paid": "ورکړل شوی", "st_unpaid": "نه دی ورکړل شوی",
        "st_partial": "ناقص", "m_cash": "نغدې", "m_bank_transfer": "بانکي لېږد", "m_cheque": "چک",
        "l_customer_title": "د پېرېدونکي د حساب بیان", "l_supplier_title": "د عرضه کوونکي د حساب بیان",
        "customer": "پېرېدونکی: {v}", "supplier": "عرضه کوونکی: {v}", "credit_limit": "د پور حد: {v} روپۍ",
        "no_bills": "د دې پېرېدونکي لپاره هیڅ بل ونه موندل شو.", "no_purchases": "له دې عرضه کوونکي څخه هیڅ پیرود نه دی ثبت.",
        "h_date": "نېټه", "h_bill": "د بل شمېره", "h_receipt": "د رسید شمېره", "h_amount": "پیسې", "h_paid": "ورکړل شوي",
        "h_balance": "پاتې", "total_billed": "ټول بلونه: {v} روپۍ", "total_paid": "ټوله ورکړه: {v} روپۍ",
        "outstanding_balance": "پاتې حساب: {v} روپۍ", "total_purchased": "ټول پیرود: {v} روپۍ",
        "outstanding_payable": "ورکول پاتې: {v} روپۍ", "computer_statement": "دا د کمپیوټر له خوا جوړ شوی بیان دی.",
        "more": "+{v} نور", "rate_title": "د نرخونو لېست", "no_items_found": "هیڅ توکی ونه موندل شو.",
        "uncategorized": "بې کتګورۍ", "h_unit": "واحد", "h_price": "بیه (روپۍ)",
        "disclaimer": "بیې د مخکې خبرتیا پرته بدلېدای شي.",
    },
    "pt": {
        "phone": "Telefone: {v}", "strn": "STRN: {v}", "generated": "Gerado em {v}",
        "thanks": "Obrigado pela preferência!", "invoice_title": "FATURA FISCAL", "invoice_no": "Fatura n.º: {v}",
        "date": "Data: {v}", "pay_status": "Status do pagamento: {v}", "pay_method": "Forma de pagamento: {v}",
        "billed_to": "Faturado para:", "address": "Endereço: {v}", "h_item": "Item", "h_qty": "Qtd",
        "h_rate": "Preço", "h_taxable": "Base", "h_taxpct": "Imp.%", "h_tax": "Imposto", "h_hsn": "HSN",
        "h_desc": "Descrição", "h_total": "Total",
        "inc_note": "* Os preços incluem imposto sobre vendas; o imposto é mostrado separadamente para referência.",
        "t_taxable": "Valor tributável total", "t_addtax": "Mais: imposto sobre vendas", "t_discount": "Menos: desconto",
        "t_roundoff": "Arredondamento", "t_grand": "TOTAL GERAL", "hsn_summary": "Resumo HSN:",
        "amount_paid": "Valor pago: Rs. {v}", "outstanding": "Em aberto: Rs. {v}", "items_lbl": "Itens:",
        "no_items": "Sem itens", "total_rs": "Total: Rs. {v}", "pay_jazz": "Pague via JazzCash: {v}",
        "for_shop": "Por {v}", "signatory": "Assinante autorizado",
        "computer_invoice": "Esta é uma fatura gerada por computador.", "st_paid": "Paga", "st_unpaid": "Não paga",
        "st_partial": "Parcial", "m_cash": "Dinheiro", "m_bank_transfer": "Transferência bancária", "m_cheque": "Cheque",
        "l_customer_title": "EXTRATO DE CONTA DO CLIENTE", "l_supplier_title": "EXTRATO DE CONTA DO FORNECEDOR",
        "customer": "Cliente: {v}", "supplier": "Fornecedor: {v}", "credit_limit": "Limite de crédito: Rs. {v}",
        "no_bills": "Nenhuma fatura encontrada para este cliente.", "no_purchases": "Nenhuma compra registrada deste fornecedor.",
        "h_date": "Data", "h_bill": "N.º fat.", "h_receipt": "N.º recibo", "h_amount": "Valor", "h_paid": "Pago",
        "h_balance": "Saldo", "total_billed": "Total faturado: Rs. {v}", "total_paid": "Total pago: Rs. {v}",
        "outstanding_balance": "Saldo em aberto: Rs. {v}", "total_purchased": "Total comprado: Rs. {v}",
        "outstanding_payable": "A pagar em aberto: Rs. {v}", "computer_statement": "Este é um extrato gerado por computador.",
        "more": "+{v} mais", "rate_title": "TABELA DE PREÇOS", "no_items_found": "Nenhum item encontrado.",
        "uncategorized": "Sem categoria", "h_unit": "Unidade", "h_price": "Preço (Rs.)",
        "disclaimer": "Preços sujeitos a alteração sem aviso prévio.",
    },
    "ru": {
        "phone": "Телефон: {v}", "strn": "STRN: {v}", "generated": "Сформировано {v}",
        "thanks": "Спасибо за покупку!", "invoice_title": "НАЛОГОВЫЙ СЧЁТ", "invoice_no": "Счёт №: {v}",
        "date": "Дата: {v}", "pay_status": "Статус оплаты: {v}", "pay_method": "Способ оплаты: {v}",
        "billed_to": "Плательщик:", "address": "Адрес: {v}", "h_item": "Товар", "h_qty": "Кол.",
        "h_rate": "Цена", "h_taxable": "Обл. сумма", "h_taxpct": "Налог%", "h_tax": "Налог", "h_hsn": "HSN",
        "h_desc": "Описание", "h_total": "Итого",
        "inc_note": "* Цены включают налог с продаж; налог показан отдельно для справки.",
        "t_taxable": "Всего облагаемая стоимость", "t_addtax": "Плюс: налог с продаж", "t_discount": "Минус: скидка",
        "t_roundoff": "Округление", "t_grand": "ОБЩИЙ ИТОГ", "hsn_summary": "Сводка HSN:",
        "amount_paid": "Оплачено: {v} руп.", "outstanding": "Задолженность: {v} руп.", "items_lbl": "Товары:",
        "no_items": "Нет товаров", "total_rs": "Итого: {v} руп.", "pay_jazz": "Оплата через JazzCash: {v}",
        "for_shop": "От имени {v}", "signatory": "Уполномоченное лицо",
        "computer_invoice": "Это счёт, сформированный компьютером.", "st_paid": "Оплачено", "st_unpaid": "Не оплачено",
        "st_partial": "Частично", "m_cash": "Наличные", "m_bank_transfer": "Банковский перевод", "m_cheque": "Чек",
        "l_customer_title": "ВЫПИСКА ПО СЧЁТУ КЛИЕНТА", "l_supplier_title": "ВЫПИСКА ПО СЧЁТУ ПОСТАВЩИКА",
        "customer": "Клиент: {v}", "supplier": "Поставщик: {v}", "credit_limit": "Кредитный лимит: {v} руп.",
        "no_bills": "Счета для этого клиента не найдены.", "no_purchases": "Закупок у этого поставщика не зарегистрировано.",
        "h_date": "Дата", "h_bill": "Счёт №", "h_receipt": "Квит. №", "h_amount": "Сумма", "h_paid": "Оплачено",
        "h_balance": "Остаток", "total_billed": "Всего выставлено: {v} руп.", "total_paid": "Всего оплачено: {v} руп.",
        "outstanding_balance": "Непогашенный остаток: {v} руп.", "total_purchased": "Всего закуплено: {v} руп.",
        "outstanding_payable": "Задолженность к оплате: {v} руп.", "computer_statement": "Это выписка, сформированная компьютером.",
        "more": "+ещё {v}", "rate_title": "ПРАЙС-ЛИСТ", "no_items_found": "Товары не найдены.",
        "uncategorized": "Без категории", "h_unit": "Ед.", "h_price": "Цена (руп.)",
        "disclaimer": "Цены могут быть изменены без предупреждения.",
    },
    "sd": {
        "phone": "فون: {v}", "strn": "STRN: {v}", "generated": "ٺاهڻ جي تاريخ: {v}",
        "thanks": "توهان جي واپار لاءِ مهرباني!", "invoice_title": "ٽيڪس انوائس", "invoice_no": "انوائس نمبر: {v}",
        "date": "تاريخ: {v}", "pay_status": "ادائيگي جي حالت: {v}", "pay_method": "ادائيگي جو طريقو: {v}",
        "billed_to": "بل وصول ڪندڙ:", "address": "پتو: {v}", "h_item": "شيءِ", "h_qty": "مقدار",
        "h_rate": "ريٽ", "h_taxable": "ٽيڪس لاڳو", "h_taxpct": "ٽيڪس%", "h_tax": "ٽيڪس", "h_hsn": "HSN",
        "h_desc": "تفصيل", "h_total": "ڪل",
        "inc_note": "* قيمتن ۾ سيلز ٽيڪس شامل آهي؛ حوالي لاءِ ٽيڪس الڳ ڏيکاريو ويو آهي.",
        "t_taxable": "ڪل ٽيڪس لاڳو قيمت", "t_addtax": "شامل: سيلز ٽيڪس", "t_discount": "گھٽ: رعايت",
        "t_roundoff": "گول انگ", "t_grand": "ڪل جوڙ", "hsn_summary": "HSN خلاصو:",
        "amount_paid": "ادا ڪيل رقم: {v} روپيا", "outstanding": "بقايا: {v} روپيا", "items_lbl": "شيون:",
        "no_items": "ڪا شيءِ ناهي", "total_rs": "ڪل: {v} روپيا", "pay_jazz": "JazzCash ذريعي ادا ڪريو: {v}",
        "for_shop": "{v} لاءِ", "signatory": "مجاز دستخط ڪندڙ", "computer_invoice": "هي ڪمپيوٽر پاران ٺاهيل انوائس آهي.",
        "st_paid": "ادا ٿيل", "st_unpaid": "اڻ ادا ٿيل", "st_partial": "جزوي", "m_cash": "نقد",
        "m_bank_transfer": "بئنڪ ٽرانسفر", "m_cheque": "چيڪ", "l_customer_title": "گراهڪ جو کاتو بيان",
        "l_supplier_title": "سپلائر جو کاتو بيان", "customer": "گراهڪ: {v}", "supplier": "سپلائر: {v}",
        "credit_limit": "ڪريڊٽ حد: {v} روپيا", "no_bills": "هن گراهڪ جو ڪو بل نه مليو.",
        "no_purchases": "هن سپلائر کان ڪا خريداري رڪارڊ ٿيل ناهي.", "h_date": "تاريخ", "h_bill": "بل نمبر",
        "h_receipt": "رسيد نمبر", "h_amount": "رقم", "h_paid": "ادا ٿيل", "h_balance": "بقايا",
        "total_billed": "ڪل بل: {v} روپيا", "total_paid": "ڪل ادائيگي: {v} روپيا", "outstanding_balance": "بقايا رقم: {v} روپيا",
        "total_purchased": "ڪل خريداري: {v} روپيا", "outstanding_payable": "ادا ڪرڻ لاءِ بقايا: {v} روپيا",
        "computer_statement": "هي ڪمپيوٽر پاران ٺاهيل بيان آهي.", "more": "+{v} وڌيڪ", "rate_title": "ريٽ لسٽ",
        "no_items_found": "ڪا شيءِ نه ملي.", "uncategorized": "بغير درجي", "h_unit": "يونٽ", "h_price": "قيمت (روپيا)",
        "disclaimer": "قيمتون اڳواٽ اطلاع کانسواءِ تبديل ٿي سگھن ٿيون.",
    },
    "sw": {
        "phone": "Simu: {v}", "strn": "STRN: {v}", "generated": "Imetengenezwa {v}",
        "thanks": "Asante kwa biashara yako!", "invoice_title": "ANKARA YA KODI", "invoice_no": "Namba ya Ankara: {v}",
        "date": "Tarehe: {v}", "pay_status": "Hali ya Malipo: {v}", "pay_method": "Njia ya Malipo: {v}",
        "billed_to": "Anayetozwa:", "address": "Anwani: {v}", "h_item": "Bidhaa", "h_qty": "Idadi",
        "h_rate": "Bei", "h_taxable": "Inayotozwa", "h_taxpct": "Kodi%", "h_tax": "Kodi", "h_hsn": "HSN",
        "h_desc": "Maelezo", "h_total": "Jumla",
        "inc_note": "* Bei zinajumuisha kodi ya mauzo; kodi inaonyeshwa kando kwa marejeo.",
        "t_taxable": "Jumla ya Thamani Inayotozwa Kodi", "t_addtax": "Ongeza: Kodi ya Mauzo", "t_discount": "Toa: Punguzo",
        "t_roundoff": "Kukadiria", "t_grand": "JUMLA KUU", "hsn_summary": "Muhtasari wa HSN:",
        "amount_paid": "Kiasi Kilicholipwa: Rs. {v}", "outstanding": "Kilichobaki: Rs. {v}", "items_lbl": "Bidhaa:",
        "no_items": "Hakuna bidhaa", "total_rs": "Jumla: Rs. {v}", "pay_jazz": "Lipa kupitia JazzCash: {v}",
        "for_shop": "Kwa {v}", "signatory": "Mtia Saini Aliyeidhinishwa",
        "computer_invoice": "Hii ni ankara iliyotengenezwa na kompyuta.", "st_paid": "Imelipwa", "st_unpaid": "Haijalipwa",
        "st_partial": "Sehemu", "m_cash": "Pesa taslimu", "m_bank_transfer": "Uhamisho wa Benki", "m_cheque": "Hundi",
        "l_customer_title": "TAARIFA YA AKAUNTI YA MTEJA", "l_supplier_title": "TAARIFA YA AKAUNTI YA MSAMBAZAJI",
        "customer": "Mteja: {v}", "supplier": "Msambazaji: {v}", "credit_limit": "Kikomo cha Mkopo: Rs. {v}",
        "no_bills": "Hakuna ankara zilizopatikana kwa mteja huyu.", "no_purchases": "Hakuna manunuzi yaliyorekodiwa kutoka kwa msambazaji huyu.",
        "h_date": "Tarehe", "h_bill": "Ankara #", "h_receipt": "Risiti #", "h_amount": "Kiasi", "h_paid": "Kimelipwa",
        "h_balance": "Salio", "total_billed": "Jumla Iliyotozwa: Rs. {v}", "total_paid": "Jumla Iliyolipwa: Rs. {v}",
        "outstanding_balance": "Salio Linalodaiwa: Rs. {v}", "total_purchased": "Jumla ya Manunuzi: Rs. {v}",
        "outstanding_payable": "Deni la Kulipa: Rs. {v}", "computer_statement": "Hii ni taarifa iliyotengenezwa na kompyuta.",
        "more": "+{v} zaidi", "rate_title": "ORODHA YA BEI", "no_items_found": "Hakuna bidhaa zilizopatikana.",
        "uncategorized": "Bila Kundi", "h_unit": "Kipimo", "h_price": "Bei (Rs.)",
        "disclaimer": "Bei zinaweza kubadilika bila taarifa.",
    },
    "tr": {
        "phone": "Telefon: {v}", "strn": "STRN: {v}", "generated": "Oluşturulma: {v}",
        "thanks": "İşiniz için teşekkürler!", "invoice_title": "VERGİ FATURASI", "invoice_no": "Fatura No: {v}",
        "date": "Tarih: {v}", "pay_status": "Ödeme Durumu: {v}", "pay_method": "Ödeme Yöntemi: {v}",
        "billed_to": "Fatura Edilen:", "address": "Adres: {v}", "h_item": "Ürün", "h_qty": "Adet",
        "h_rate": "Fiyat", "h_taxable": "Matrah", "h_taxpct": "Vergi%", "h_tax": "Vergi", "h_hsn": "HSN",
        "h_desc": "Açıklama", "h_total": "Toplam",
        "inc_note": "* Fiyatlara satış vergisi dahildir; vergi bilgi amaçlı ayrıca gösterilmiştir.",
        "t_taxable": "Toplam Vergiye Tabi Tutar", "t_addtax": "Ekle: Satış Vergisi", "t_discount": "Çıkar: İndirim",
        "t_roundoff": "Yuvarlama", "t_grand": "GENEL TOPLAM", "hsn_summary": "HSN Özeti:",
        "amount_paid": "Ödenen Tutar: Rs. {v}", "outstanding": "Kalan: Rs. {v}", "items_lbl": "Ürünler:",
        "no_items": "Ürün yok", "total_rs": "Toplam: Rs. {v}", "pay_jazz": "JazzCash ile ödeyin: {v}",
        "for_shop": "{v} adına", "signatory": "Yetkili İmza",
        "computer_invoice": "Bu, bilgisayar tarafından oluşturulmuş bir faturadır.", "st_paid": "Ödendi", "st_unpaid": "Ödenmedi",
        "st_partial": "Kısmi", "m_cash": "Nakit", "m_bank_transfer": "Banka Havalesi", "m_cheque": "Çek",
        "l_customer_title": "MÜŞTERİ HESAP EKSTRESİ", "l_supplier_title": "TEDARİKÇİ HESAP EKSTRESİ",
        "customer": "Müşteri: {v}", "supplier": "Tedarikçi: {v}", "credit_limit": "Kredi Limiti: Rs. {v}",
        "no_bills": "Bu müşteri için fatura bulunamadı.", "no_purchases": "Bu tedarikçiden kayıtlı alım yok.",
        "h_date": "Tarih", "h_bill": "Fatura #", "h_receipt": "Makbuz #", "h_amount": "Tutar", "h_paid": "Ödenen",
        "h_balance": "Bakiye", "total_billed": "Toplam Faturalanan: Rs. {v}", "total_paid": "Toplam Ödenen: Rs. {v}",
        "outstanding_balance": "Kalan Bakiye: Rs. {v}", "total_purchased": "Toplam Alım: Rs. {v}",
        "outstanding_payable": "Ödenecek Bakiye: Rs. {v}", "computer_statement": "Bu, bilgisayar tarafından oluşturulmuş bir ekstredir.",
        "more": "+{v} daha", "rate_title": "FİYAT LİSTESİ", "no_items_found": "Ürün bulunamadı.",
        "uncategorized": "Kategorisiz", "h_unit": "Birim", "h_price": "Fiyat (Rs.)",
        "disclaimer": "Fiyatlar önceden haber verilmeksizin değişebilir.",
    },
    "ur": {
        "phone": "فون: {v}", "strn": "STRN: {v}", "generated": "تیار کرنے کی تاریخ: {v}",
        "thanks": "آپ کے کاروبار کا شکریہ!", "invoice_title": "ٹیکس انوائس", "invoice_no": "انوائس نمبر: {v}",
        "date": "تاریخ: {v}", "pay_status": "ادائیگی کی حالت: {v}", "pay_method": "ادائیگی کا طریقہ: {v}",
        "billed_to": "بل وصول کنندہ:", "address": "پتہ: {v}", "h_item": "آئٹم", "h_qty": "مقدار",
        "h_rate": "ریٹ", "h_taxable": "قابلِ ٹیکس", "h_taxpct": "ٹیکس%", "h_tax": "ٹیکس", "h_hsn": "HSN",
        "h_desc": "تفصیل", "h_total": "کل",
        "inc_note": "* قیمتوں میں سیلز ٹیکس شامل ہے؛ حوالے کے لیے ٹیکس الگ دکھایا گیا ہے۔",
        "t_taxable": "کل قابلِ ٹیکس قیمت", "t_addtax": "شامل: سیلز ٹیکس", "t_discount": "منفی: رعایت",
        "t_roundoff": "گول عدد", "t_grand": "کل میزان", "hsn_summary": "HSN خلاصہ:",
        "amount_paid": "ادا شدہ رقم: {v} روپے", "outstanding": "بقایا: {v} روپے", "items_lbl": "اشیاء:",
        "no_items": "کوئی آئٹم نہیں", "total_rs": "کل: {v} روپے", "pay_jazz": "جاز کیش کے ذریعے ادائیگی کریں: {v}",
        "for_shop": "{v} کی طرف سے", "signatory": "مجاز دستخط کنندہ", "computer_invoice": "یہ کمپیوٹر سے تیار کردہ انوائس ہے۔",
        "st_paid": "ادا شدہ", "st_unpaid": "غیر ادا شدہ", "st_partial": "جزوی", "m_cash": "نقد",
        "m_bank_transfer": "بینک ٹرانسفر", "m_cheque": "چیک", "l_customer_title": "گاہک کھاتہ اسٹیٹمنٹ",
        "l_supplier_title": "سپلائر کھاتہ اسٹیٹمنٹ", "customer": "گاہک: {v}", "supplier": "سپلائر: {v}",
        "credit_limit": "کریڈٹ حد: {v} روپے", "no_bills": "اس گاہک کا کوئی بل نہیں ملا۔",
        "no_purchases": "اس سپلائر سے کوئی خریداری درج نہیں ہے۔", "h_date": "تاریخ", "h_bill": "بل نمبر",
        "h_receipt": "رسید نمبر", "h_amount": "رقم", "h_paid": "ادا شدہ", "h_balance": "بقایا",
        "total_billed": "کل بل: {v} روپے", "total_paid": "کل ادائیگی: {v} روپے", "outstanding_balance": "بقایا رقم: {v} روپے",
        "total_purchased": "کل خریداری: {v} روپے", "outstanding_payable": "قابلِ ادا بقایا: {v} روپے",
        "computer_statement": "یہ کمپیوٹر سے تیار کردہ اسٹیٹمنٹ ہے۔", "more": "+{v} مزید", "rate_title": "ریٹ لسٹ",
        "no_items_found": "کوئی آئٹم نہیں ملا۔", "uncategorized": "بلا زمرہ", "h_unit": "اکائی", "h_price": "قیمت (روپے)",
        "disclaimer": "قیمتیں بغیر اطلاع کے تبدیل ہو سکتی ہیں۔",
    },
}

_T["zh"] = {
    "phone": "电话：{v}",
    "strn": "STRN：{v}",
    "generated": "生成时间：{v}",
    "thanks": "感谢您的惠顾！",
    "invoice_title": "税务发票",
    "invoice_no": "发票号：{v}",
    "date": "日期：{v}",
    "pay_status": "付款状态：{v}",
    "pay_method": "付款方式：{v}",
    "billed_to": "收票方：",
    "address": "地址：{v}",
    "h_item": "商品",
    "h_qty": "数量",
    "h_rate": "单价",
    "h_taxable": "应税额",
    "h_taxpct": "税率%",
    "h_tax": "税额",
    "h_hsn": "HSN",
    "h_desc": "说明",
    "h_total": "合计",
    "inc_note": "* 价格已含销售税；税额单独列出，仅供参考。",
    "t_taxable": "应税价值合计",
    "t_addtax": "加：销售税",
    "t_discount": "减：折扣",
    "t_roundoff": "四舍五入",
    "t_grand": "总计",
    "hsn_summary": "HSN 汇总：",
    "amount_paid": "已付金额：{v}卢比",
    "outstanding": "未付：{v}卢比",
    "items_lbl": "商品：",
    "no_items": "无商品",
    "total_rs": "合计：{v}卢比",
    "pay_jazz": "通过 JazzCash 付款：{v}",
    "for_shop": "{v} 敬上",
    "signatory": "授权签字人",
    "computer_invoice": "本发票由计算机生成。",
    "st_paid": "已付",
    "st_unpaid": "未付",
    "st_partial": "部分已付",
    "m_cash": "现金",
    "m_bank_transfer": "银行转账",
    "m_cheque": "支票",
    "l_customer_title": "客户对账单",
    "l_supplier_title": "供应商对账单",
    "customer": "客户：{v}",
    "supplier": "供应商：{v}",
    "credit_limit": "信用额度：{v}卢比",
    "no_bills": "未找到该客户的账单。",
    "no_purchases": "未记录该供应商的采购。",
    "h_date": "日期",
    "h_bill": "账单号",
    "h_receipt": "收据号",
    "h_amount": "金额",
    "h_paid": "已付",
    "h_balance": "余额",
    "total_billed": "账单总额：{v}卢比",
    "total_paid": "已付总额：{v}卢比",
    "outstanding_balance": "未结余额：{v}卢比",
    "total_purchased": "采购总额：{v}卢比",
    "outstanding_payable": "应付未结：{v}卢比",
    "computer_statement": "本对账单由计算机生成。",
    "more": "另有 {v} 项",
    "rate_title": "价目表",
    "no_items_found": "未找到商品。",
    "uncategorized": "未分类",
    "h_unit": "单位",
    "h_price": "价格（卢比）",
    "disclaimer": "价格如有变动，恕不另行通知。",
}

_T["ja"] = {
    "phone": "電話：{v}",
    "strn": "STRN：{v}",
    "generated": "作成日時：{v}",
    "thanks": "ご利用ありがとうございます！",
    "invoice_title": "税務請求書",
    "invoice_no": "請求書番号：{v}",
    "date": "日付：{v}",
    "pay_status": "支払状況：{v}",
    "pay_method": "支払方法：{v}",
    "billed_to": "請求先：",
    "address": "住所：{v}",
    "h_item": "品名",
    "h_qty": "数量",
    "h_rate": "単価",
    "h_taxable": "課税額",
    "h_taxpct": "税率%",
    "h_tax": "税額",
    "h_hsn": "HSN",
    "h_desc": "内容",
    "h_total": "合計",
    "inc_note": "※価格には売上税が含まれています。税額は参考として別に表示しています。",
    "t_taxable": "課税対象額合計",
    "t_addtax": "加算：売上税",
    "t_discount": "減算：値引き",
    "t_roundoff": "端数調整",
    "t_grand": "総合計",
    "hsn_summary": "HSN 集計：",
    "amount_paid": "支払済額：{v}ルピー",
    "outstanding": "未払い：{v}ルピー",
    "items_lbl": "品目：",
    "no_items": "品目なし",
    "total_rs": "合計：{v}ルピー",
    "pay_jazz": "JazzCashで支払う：{v}",
    "for_shop": "{v} 発行",
    "signatory": "承認者署名",
    "computer_invoice": "この請求書はコンピューターで作成されています。",
    "st_paid": "支払済",
    "st_unpaid": "未払い",
    "st_partial": "一部支払",
    "m_cash": "現金",
    "m_bank_transfer": "銀行振込",
    "m_cheque": "小切手",
    "l_customer_title": "顧客元帳明細",
    "l_supplier_title": "仕入先元帳明細",
    "customer": "顧客：{v}",
    "supplier": "仕入先：{v}",
    "credit_limit": "与信限度額：{v}ルピー",
    "no_bills": "この顧客の請求書が見つかりません。",
    "no_purchases": "この仕入先からの仕入記録はありません。",
    "h_date": "日付",
    "h_bill": "請求書番号",
    "h_receipt": "領収書番号",
    "h_amount": "金額",
    "h_paid": "支払済",
    "h_balance": "残高",
    "total_billed": "請求総額：{v}ルピー",
    "total_paid": "支払総額：{v}ルピー",
    "outstanding_balance": "未払残高：{v}ルピー",
    "total_purchased": "仕入総額：{v}ルピー",
    "outstanding_payable": "買掛未払：{v}ルピー",
    "computer_statement": "この明細書はコンピューターで作成されています。",
    "more": "他 {v} 件",
    "rate_title": "価格表",
    "no_items_found": "品目が見つかりません。",
    "uncategorized": "未分類",
    "h_unit": "単位",
    "h_price": "価格（ルピー）",
    "disclaimer": "価格は予告なく変更される場合があります。",
}

_T["ko"] = {
    "phone": "전화: {v}",
    "strn": "STRN: {v}",
    "generated": "생성일: {v}",
    "thanks": "이용해 주셔서 감사합니다!",
    "invoice_title": "세금계산서",
    "invoice_no": "송장 번호: {v}",
    "date": "날짜: {v}",
    "pay_status": "결제 상태: {v}",
    "pay_method": "결제 방법: {v}",
    "billed_to": "청구 대상:",
    "address": "주소: {v}",
    "h_item": "품목",
    "h_qty": "수량",
    "h_rate": "단가",
    "h_taxable": "과세액",
    "h_taxpct": "세율%",
    "h_tax": "세액",
    "h_hsn": "HSN",
    "h_desc": "설명",
    "h_total": "합계",
    "inc_note": "* 가격에는 판매세가 포함되어 있으며, 세액은 참고용으로 별도 표시됩니다.",
    "t_taxable": "과세 대상 금액 합계",
    "t_addtax": "가산: 판매세",
    "t_discount": "차감: 할인",
    "t_roundoff": "반올림",
    "t_grand": "총합계",
    "hsn_summary": "HSN 요약:",
    "amount_paid": "결제 금액: {v}루피",
    "outstanding": "미결제: {v}루피",
    "items_lbl": "품목:",
    "no_items": "품목 없음",
    "total_rs": "합계: {v}루피",
    "pay_jazz": "JazzCash로 결제: {v}",
    "for_shop": "{v} 발행",
    "signatory": "승인 서명자",
    "computer_invoice": "이 송장은 컴퓨터로 생성되었습니다.",
    "st_paid": "결제 완료",
    "st_unpaid": "미결제",
    "st_partial": "부분 결제",
    "m_cash": "현금",
    "m_bank_transfer": "계좌 이체",
    "m_cheque": "수표",
    "l_customer_title": "고객 원장 명세서",
    "l_supplier_title": "공급업체 원장 명세서",
    "customer": "고객: {v}",
    "supplier": "공급업체: {v}",
    "credit_limit": "여신 한도: {v}루피",
    "no_bills": "이 고객의 청구서가 없습니다.",
    "no_purchases": "이 공급업체의 구매 기록이 없습니다.",
    "h_date": "날짜",
    "h_bill": "청구서 번호",
    "h_receipt": "영수증 번호",
    "h_amount": "금액",
    "h_paid": "결제",
    "h_balance": "잔액",
    "total_billed": "청구 총액: {v}루피",
    "total_paid": "결제 총액: {v}루피",
    "outstanding_balance": "미결제 잔액: {v}루피",
    "total_purchased": "구매 총액: {v}루피",
    "outstanding_payable": "미지급금: {v}루피",
    "computer_statement": "이 명세서는 컴퓨터로 생성되었습니다.",
    "more": "{v}개 더",
    "rate_title": "가격표",
    "no_items_found": "품목을 찾을 수 없습니다.",
    "uncategorized": "미분류",
    "h_unit": "단위",
    "h_price": "가격 (루피)",
    "disclaimer": "가격은 예고 없이 변경될 수 있습니다.",
}

# Price / stock history PDF (utils/pdf_history.py), in the order of EN's new keys:
# title, stock title, cost price, change, by, previous, new, note, no entries.
_HIST_KEYS = ("ph_title", "sh_title", "h_cost", "h_change", "h_by", "h_prev", "h_new", "h_note", "no_history")
_HIST = {
    "ar": ("سجل الأسعار", "سجل تعديلات المخزون", "سعر التكلفة", "التغيير", "بواسطة", "السابق", "الجديد", "ملاحظة", "لا توجد سجلات."),
    "bn": ("মূল্যের ইতিহাস", "স্টক সমন্বয়ের ইতিহাস", "ক্রয়মূল্য", "পরিবর্তন", "যিনি করেছেন", "আগের", "নতুন", "নোট", "কোনো এন্ট্রি নেই।"),
    "de": ("PREISVERLAUF", "VERLAUF DER BESTANDSKORREKTUREN", "Einkaufspreis", "Änderung", "Von", "Vorher", "Neu", "Notiz", "Keine Einträge vorhanden."),
    "es": ("HISTORIAL DE PRECIOS", "HISTORIAL DE AJUSTES DE EXISTENCIAS", "Precio de costo", "Cambio", "Por", "Anterior", "Nuevo", "Nota", "Sin registros."),
    "fa": ("تاریخچه قیمت", "تاریخچه اصلاح موجودی", "قیمت تمام‌شده", "تغییر", "توسط", "قبلی", "جدید", "یادداشت", "موردی ثبت نشده است."),
    "fr": ("HISTORIQUE DES PRIX", "HISTORIQUE DES AJUSTEMENTS DE STOCK", "Prix de revient", "Variation", "Par", "Avant", "Après", "Note", "Aucune entrée."),
    "hi": ("मूल्य इतिहास", "स्टॉक सुधार का इतिहास", "लागत मूल्य", "बदलाव", "द्वारा", "पहले", "नया", "नोट", "कोई प्रविष्टि नहीं।"),
    "id": ("RIWAYAT HARGA", "RIWAYAT PENYESUAIAN STOK", "Harga pokok", "Perubahan", "Oleh", "Sebelumnya", "Baru", "Catatan", "Belum ada catatan."),
    "ja": ("価格履歴", "在庫調整履歴", "仕入価格", "変動", "担当", "変更前", "変更後", "メモ", "記録はありません。"),
    "ko": ("가격 이력", "재고 조정 이력", "원가", "변동", "작성자", "이전", "이후", "메모", "기록이 없습니다."),
    "pa": ("ਕੀਮਤ ਦਾ ਇਤਿਹਾਸ", "ਸਟਾਕ ਸੁਧਾਰ ਦਾ ਇਤਿਹਾਸ", "ਲਾਗਤ ਕੀਮਤ", "ਬਦਲਾਅ", "ਵੱਲੋਂ", "ਪਹਿਲਾਂ", "ਨਵਾਂ", "ਨੋਟ", "ਕੋਈ ਐਂਟਰੀ ਨਹੀਂ।"),
    "ps": ("د بیې تاریخچه", "د ذخیرې د سمونونو تاریخچه", "د لګښت بیه", "بدلون", "د لوري", "مخکینی", "نوی", "یادښت", "هیڅ ثبت شوی نه دی."),
    "pt": ("HISTÓRICO DE PREÇOS", "HISTÓRICO DE AJUSTES DE ESTOQUE", "Preço de custo", "Variação", "Por", "Anterior", "Novo", "Nota", "Nenhum registro."),
    "ru": ("ИСТОРИЯ ЦЕН", "ИСТОРИЯ КОРРЕКТИРОВОК ОСТАТКОВ", "Закупочная цена", "Изменение", "Кем", "Было", "Стало", "Заметка", "Записей нет."),
    "sd": ("قيمت جي تاريخ", "اسٽاڪ درستين جي تاريخ", "خرچ جي قيمت", "تبديلي", "طرفان", "اڳيون", "نئون", "نوٽ", "ڪي به اندراج ناهن."),
    "sw": ("HISTORIA YA BEI", "HISTORIA YA MAREKEBISHO YA HIFADHI", "Bei ya gharama", "Mabadiliko", "Na", "Kabla", "Mpya", "Maelezo", "Hakuna rekodi."),
    "tr": ("FİYAT GEÇMİŞİ", "STOK DÜZELTME GEÇMİŞİ", "Maliyet fiyatı", "Değişim", "Yapan", "Önceki", "Yeni", "Not", "Kayıt yok."),
    "ur": ("قیمت کی تاریخ", "اسٹاک درستگی کی تاریخ", "لاگت کی قیمت", "تبدیلی", "بذریعہ", "پہلے", "نیا", "نوٹ", "کوئی اندراج نہیں۔"),
    "zh": ("价格记录", "库存调整记录", "成本价", "变动", "操作人", "调整前", "调整后", "备注", "暂无记录。"),
}
for _lang, _words in _HIST.items():
    _T[_lang].update(zip(_HIST_KEYS, _words))

SUPPORTED = {"en", *_T}
RTL = {"ar", "fa", "ps", "sd", "ur"}

_CURRENCY = {
    "zh": ("", "卢比"),
    "ja": ("", "ルピー"),
    "ko": ("", "루피"),
    "ar": ("", " روبية"),
    "bn": ("", " রুপি"),
    "fa": ("", " روپیه"),
    "ps": ("", " روپۍ"),
    "ru": ("", " руп."),
    "sd": ("", " روپيا"),
    "ur": ("", " روپے"),
    "hi": ("रु ", ""),
    "pa": ("ਰੁ ", ""),
}

_UNIT_KEYS = ("piece", "kg", "meter", "box", "dozen", "liter", "bag")
_UNITS = {
    "zh": ("件", "千克", "米", "盒", "打", "升", "袋"),
    "ja": ("個", "kg", "メートル", "箱", "ダース", "リットル", "袋"),
    "ko": ("개", "kg", "미터", "상자", "다스", "리터", "포대"),
    "ar": ("قطعة", "كجم", "متر", "صندوق", "دزينة", "لتر", "كيس"),
    "bn": ("পিস", "কেজি", "মিটার", "বাক্স", "ডজন", "লিটার", "ব্যাগ"),
    "de": ("Stück", "kg", "Meter", "Karton", "Dutzend", "Liter", "Sack"),
    "es": ("pieza", "kg", "metro", "caja", "docena", "litro", "bolsa"),
    "fa": ("عدد", "کیلوگرم", "متر", "جعبه", "دوجین", "لیتر", "کیسه"),
    "fr": ("pièce", "kg", "mètre", "boîte", "douzaine", "litre", "sac"),
    "hi": ("पीस", "किलो", "मीटर", "डिब्बा", "दर्जन", "लीटर", "बोरी"),
    "id": ("buah", "kg", "meter", "kotak", "lusin", "liter", "karung"),
    "pa": ("ਪੀਸ", "ਕਿਲੋ", "ਮੀਟਰ", "ਡੱਬਾ", "ਦਰਜਨ", "ਲੀਟਰ", "ਬੋਰੀ"),
    "ps": ("ټوټه", "کیلو", "متر", "بکس", "درجن", "لیتر", "بوری"),
    "pt": ("peça", "kg", "metro", "caixa", "dúzia", "litro", "saco"),
    "ru": ("шт.", "кг", "м", "коробка", "дюжина", "л", "мешок"),
    "sd": ("دانو", "ڪلو", "ميٽر", "دٻو", "درجن", "ليٽر", "ٻوري"),
    "sw": ("kipande", "kg", "mita", "boksi", "dazeni", "lita", "mfuko"),
    "tr": ("adet", "kg", "metre", "kutu", "düzine", "litre", "çuval"),
    "ur": ("عدد", "کلو", "میٹر", "ڈبہ", "درجن", "لیٹر", "بوری"),
}


def pdf_lang(code: str | None) -> str:
    """Language the PDF is written in: the app language when its script has a
    bundled font, otherwise English."""
    code = (code or "en").strip().lower()[:2]
    return code if code in SUPPORTED else "en"


class Labels:
    def __init__(self, lang: str | None):
        self.lang = pdf_lang(lang)
        self._t = {**EN, **_T.get(self.lang, {})}
        self.names: dict[tuple[str, str], str] = {}

    def load_names(self, pairs) -> None:
        """Fetch the item/party/category names to print in this PDF's language."""
        from utils import name_translate

        self.names = name_translate.mapping(self.lang, pairs)

    def n(self, kind: str, text):
        """A name as it should print: its rendering in this language, else as typed."""
        return self.names.get((kind, text), text)

    def money(self, amount: str) -> str:
        pre, suf = _CURRENCY.get(self.lang, ("Rs. ", ""))
        return f"{pre}{amount}{suf}"

    def unit(self, unit: str | None) -> str:
        u = (unit or "piece").strip()
        names = _UNITS.get(self.lang)
        if names and u.lower() in _UNIT_KEYS:
            return names[_UNIT_KEYS.index(u.lower())]
        return u

    def __call__(self, key: str, v=None) -> str:
        text = self._t[key]
        return text.format(v=v) if v is not None else text

    @property
    def rtl(self) -> bool:
        return self.lang in RTL

    @property
    def align(self) -> str:
        return "R" if self.rtl else "L"

    def status(self, value: str | None) -> str:
        key = {"paid": "st_paid", "unpaid": "st_unpaid", "partial": "st_partial"}.get((value or "unpaid").lower())
        return self(key) if key else (value or "").capitalize()

    def method(self, value: str | None) -> str:
        key = {"cash": "m_cash", "bank_transfer": "m_bank_transfer", "cheque": "m_cheque"}.get((value or "cash").lower())
        return self(key) if key else (value or "").replace("_", " ").capitalize()

    def when(self, dt: datetime) -> str:
        return dt.strftime("%d-%b-%Y %I:%M %p") if self.lang == "en" else dt.strftime("%d-%m-%Y %H:%M")

    def day(self, dt: datetime) -> str:
        return dt.strftime("%d-%b-%y") if self.lang == "en" else dt.strftime("%d-%m-%y")
